from typing import List
from datetime import datetime

import gpxpy
import gpxpy.gpx

from app.models.schemas import RoutePoint


def generate_gpx(route: List[RoutePoint], name: str = "EveryStreet Route") -> str:
    """
    Generate a GPX file from a route.

    Args:
        route: List of route points with coordinates
        name: Name for the GPX track

    Returns:
        GPX file content as string
    """
    gpx = gpxpy.gpx.GPX()

    # Create track
    gpx_track = gpxpy.gpx.GPXTrack()
    gpx_track.name = name
    gpx_track.description = f"Route generated by EveryStreet Mapper on {datetime.now().strftime('%Y-%m-%d')}"
    gpx.tracks.append(gpx_track)

    # Create segment
    gpx_segment = gpxpy.gpx.GPXTrackSegment()
    gpx_track.segments.append(gpx_segment)

    # Add points
    for point in route:
        gpx_point = gpxpy.gpx.GPXTrackPoint(
            latitude=point.lat,
            longitude=point.lng,
            name=point.street_name
        )
        gpx_segment.points.append(gpx_point)

    return gpx.to_xml()


def generate_gpx_with_waypoints(
    route: List[RoutePoint],
    name: str = "EveryStreet Route",
    include_waypoints: bool = False
) -> str:
    """
    Generate a GPX file with optional waypoints for turn-by-turn navigation.

    Args:
        route: List of route points with coordinates
        name: Name for the GPX track
        include_waypoints: Whether to include waypoints at street changes

    Returns:
        GPX file content as string
    """
    gpx = gpxpy.gpx.GPX()

    # Create track
    gpx_track = gpxpy.gpx.GPXTrack()
    gpx_track.name = name
    gpx_track.description = f"Route generated by EveryStreet Mapper on {datetime.now().strftime('%Y-%m-%d')}"
    gpx.tracks.append(gpx_track)

    # Create segment
    gpx_segment = gpxpy.gpx.GPXTrackSegment()
    gpx_track.segments.append(gpx_segment)

    # Add points and optionally waypoints
    current_street = None
    waypoint_count = 0

    for point in route:
        # Add track point
        gpx_point = gpxpy.gpx.GPXTrackPoint(
            latitude=point.lat,
            longitude=point.lng
        )
        gpx_segment.points.append(gpx_point)

        # Add waypoint at street changes
        if include_waypoints and point.street_name and point.street_name != current_street:
            waypoint_count += 1
            waypoint = gpxpy.gpx.GPXWaypoint(
                latitude=point.lat,
                longitude=point.lng,
                name=f"{waypoint_count}. {point.street_name}"
            )
            gpx.waypoints.append(waypoint)
            current_street = point.street_name

    return gpx.to_xml()
